//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SessionDemoApp.LongRestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LongRestService.DelayServiceSoap")]
    public interface DelayServiceSoap {
        
        // CODEGEN: Generating message contract since element name DelayResponseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelayResponse", ReplyAction="*")]
        SessionDemoApp.LongRestService.DelayResponseResponse DelayResponse(SessionDemoApp.LongRestService.DelayResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelayResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<SessionDemoApp.LongRestService.DelayResponseResponse> DelayResponseAsync(SessionDemoApp.LongRestService.DelayResponseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelayResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelayResponse", Namespace="http://tempuri.org/", Order=0)]
        public SessionDemoApp.LongRestService.DelayResponseRequestBody Body;
        
        public DelayResponseRequest() {
        }
        
        public DelayResponseRequest(SessionDemoApp.LongRestService.DelayResponseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelayResponseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int delayAmount;
        
        public DelayResponseRequestBody() {
        }
        
        public DelayResponseRequestBody(int delayAmount) {
            this.delayAmount = delayAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelayResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelayResponseResponse", Namespace="http://tempuri.org/", Order=0)]
        public SessionDemoApp.LongRestService.DelayResponseResponseBody Body;
        
        public DelayResponseResponse() {
        }
        
        public DelayResponseResponse(SessionDemoApp.LongRestService.DelayResponseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DelayResponseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DelayResponseResult;
        
        public DelayResponseResponseBody() {
        }
        
        public DelayResponseResponseBody(string DelayResponseResult) {
            this.DelayResponseResult = DelayResponseResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DelayServiceSoapChannel : SessionDemoApp.LongRestService.DelayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DelayServiceSoapClient : System.ServiceModel.ClientBase<SessionDemoApp.LongRestService.DelayServiceSoap>, SessionDemoApp.LongRestService.DelayServiceSoap {
        
        public DelayServiceSoapClient() {
        }
        
        public DelayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DelayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SessionDemoApp.LongRestService.DelayResponseResponse SessionDemoApp.LongRestService.DelayServiceSoap.DelayResponse(SessionDemoApp.LongRestService.DelayResponseRequest request) {
            return base.Channel.DelayResponse(request);
        }
        
        public string DelayResponse(int delayAmount) {
            SessionDemoApp.LongRestService.DelayResponseRequest inValue = new SessionDemoApp.LongRestService.DelayResponseRequest();
            inValue.Body = new SessionDemoApp.LongRestService.DelayResponseRequestBody();
            inValue.Body.delayAmount = delayAmount;
            SessionDemoApp.LongRestService.DelayResponseResponse retVal = ((SessionDemoApp.LongRestService.DelayServiceSoap)(this)).DelayResponse(inValue);
            return retVal.Body.DelayResponseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SessionDemoApp.LongRestService.DelayResponseResponse> SessionDemoApp.LongRestService.DelayServiceSoap.DelayResponseAsync(SessionDemoApp.LongRestService.DelayResponseRequest request) {
            return base.Channel.DelayResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SessionDemoApp.LongRestService.DelayResponseResponse> DelayResponseAsync(int delayAmount) {
            SessionDemoApp.LongRestService.DelayResponseRequest inValue = new SessionDemoApp.LongRestService.DelayResponseRequest();
            inValue.Body = new SessionDemoApp.LongRestService.DelayResponseRequestBody();
            inValue.Body.delayAmount = delayAmount;
            return ((SessionDemoApp.LongRestService.DelayServiceSoap)(this)).DelayResponseAsync(inValue);
        }
    }
}
